# Change these first
owner: DevanTheDude # Your GitHub organization or username, where this repository lives
repo: DTDHomelab # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: DTDHomelab
    url: https://dtdhomelab.com/
    __dangerous__disable_verify_peer: true
  - name: Stable Diffusion
    url: https://artstatus.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "False"
  - name: Wiki
    url: https://wiki.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
  - name: PHP
    url: https://php.dtdhomelab.com/
    __dangerous__disable_verify_peer: true

status-website:
  cname: status.dtdhomelab.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DTDHomelab
  introTitle: "DTDHomelab Status Page"
  introMessage: View status all services hosted on DTDServer
  navbar:
    - title: Status
      href: /
    - title: Wiki
      href: https://wiki.dtdhomelab.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
