# Change these first
owner: DevanTheDude # Your GitHub organization or username, where this repository lives
repo: DTDHomelab # The name of this repository

sites:
  - name: DTDHomelab Internet
    check: "tcp-ping"
    url: dtdhomelab.com
    port: 443
    __dangerous__disable_verify_peer: true
  - name: Web Server
    url: https://statuscheck.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "webOff"
  - name: Stable Diffusion
    url: https://statuscheck.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "artOff"
  - name: Wiki
    url: https://wiki.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
  - name: Remote Access 
    url: https://statuscheck.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "remoteAccessOff"
  - name: PHP
    url: https://php.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
  - name: SQL
    url: https://statuscheck.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "sqlOff"
  - name: Plex
    url: https://statuscheck.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "plexOff"
  - name: Health Dashboard
    url: https://statuscheck.dtdhomelab.com/
    __dangerous__disable_verify_peer: true
    __dangerous__body_down: "healthOff"

status-website:
  cname: status.dtdhomelab.com
  logoUrl: https://i.imgur.com/Vgk4r0t.png
  links:
    - rel: stylesheet
      href: https://status.dtdhomelab.com/themes/dtdstyle.css
  name: DTDHomelab
  introTitle: "DTDHomelab Status Page"
  introMessage: View status all services hosted on DTDServer
  navbar:
    - title: Status
      href: /
    - title: Health
      href: https://health.dtdhomelab.com/?theme=dark
